<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    
    <FileVersion>$(ProductVersion)</FileVersion>
    <Version>1.5.1-dev.1</Version>
    <Authors>https://github.com/asvol</Authors>
    <Company>https://github.com/asvol</Company>
    <Copyright>https://github.com/asvol</Copyright>
    <PackageProjectUrl>https://github.com/asvol/asv-sdr</PackageProjectUrl>
    <RepositoryUrl>https://github.com/asvol/asv-sdr</RepositoryUrl>
    <PackageTags />
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Asv.Sdr\Asv.Sdr.csproj" />
  </ItemGroup>
</Project>