<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Asv.Common" Version="$(AsvCommonVersion)" />
    <PackageReference Include="Asv.IO" Version="$(AsvCommonVersion)" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="MathNet.Filtering" Version="0.7.0" />
  </ItemGroup>
</Project>
