<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworksValue)</TargetFrameworks>
    <FileVersion>$(ProductVersion)</FileVersion>
    <Version>1.5.15</Version>
    <PackageVersion>$(ProductVersion)</PackageVersion>
    <LangVersion>latest</LangVersion>
    <Authors>https://github.com/asv-soft</Authors>
    <Company>https://github.com/asv-soft</Company>
    <Copyright>https://github.com/asv-soft</Copyright>
    <PackageProjectUrl>https://github.com/asv-soft/asv-sdr</PackageProjectUrl>
    <RepositoryUrl>https://github.com/asv-soft/asv-sdr</RepositoryUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' " />
  <ItemGroup>
    <Compile Update="Libs.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Libs.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Asv.Common" Version="$(AsvCommonVersion)" />
    <PackageReference Include="ZLogger" Version="$(ZLoggerVersion)" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Libs.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Libs.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>