<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        
        <FileVersion>$(ProductVersion)</FileVersion>
        <Version>$(ProductVersion)</Version>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asv.Avalonia.Toolkit" Version="$(AsvAvaloniaToolkitVersion)" />
        <PackageReference Include="Asv.Common" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.Cfg" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.IO" Version="$(AsvCommonVersion)" />
        
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="$(AvaloniaVersion)" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
        <PackageReference Include="ScottPlot.Avalonia" Version="5.0.34" />

        <PackageReference Include="System.Composition" Version="$(CompositionVersion)"/>
        <PackageReference Include="FluentAvaloniaUI" Version="$(FluentAvaloniaUIVersion)"/>
        <PackageReference Include="Material.Icons.Avalonia" Version="$(MaterialIconsAvaloniaVersion)"/>

        <PackageReference Include="ReactiveUI" Version="19.5.41" />
        <PackageReference Include="ReactiveUI.Fody" Version="$(ReactiveUIVersion)"/>
        <PackageReference Include="ReactiveUI.Validation" Version="$(ReactiveUIValidationVersion)"/>
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Views\MainView.axaml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Asv.Sdr.AdSdr\Asv.Sdr.AdSdr.csproj" />
      <ProjectReference Include="..\Asv.Sdr.LimeSdr\Asv.Sdr.LimeSdr.csproj" />
      <ProjectReference Include="..\Asv.Sdr.SignalHound\Asv.Sdr.SignalHound.csproj" />
    </ItemGroup>
</Project>
