<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        
        <FileVersion>$(ProductVersion)</FileVersion>
        <Version>$(ProductVersion)</Version>
        <CodeAnalysisRuleSet>../CodeStyle.ruleset</CodeAnalysisRuleSet>
        <WarningsAsErrors>
            CS0169,
            CS0618,
            CS1502,
            CS1503,
            CS8524,
            CS8600,
            CS8601,
            CS8602,
            CS8603,
            CS8604,
            CS8625,
            CS8629,
            CS8762,
            CA1510,
            CA1851
        </WarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asv.Avalonia.Toolkit" Version="$(AsvAvaloniaToolkitVersion)" />
        <PackageReference Include="Asv.Common" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.Cfg" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.IO" Version="$(AsvCommonVersion)" />
        
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="$(AvaloniaVersion)" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Roslynator.Analyzers" Version="4.12.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ScottPlot.Avalonia" Version="5.0.34" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="System.Composition" Version="$(CompositionVersion)"/>
        <PackageReference Include="FluentAvaloniaUI" Version="$(FluentAvaloniaUIVersion)"/>
        <PackageReference Include="Material.Icons.Avalonia" Version="$(MaterialIconsAvaloniaVersion)"/>

        <PackageReference Include="ReactiveUI" Version="$(ReactiveUIVersion)"/>
        <PackageReference Include="ReactiveUI.Fody" Version="$(ReactiveUIVersion)"/>
        <PackageReference Include="ReactiveUI.Validation" Version="$(ReactiveUIValidationVersion)"/>
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Views\MainView.axaml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Asv.Sdr.LimeSdr\Asv.Sdr.LimeSdr.csproj" />
      <ProjectReference Include="..\Asv.Sdr.SignalHound\Asv.Sdr.SignalHound.csproj" />
    </ItemGroup>
</Project>
