<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Asv.Sdr\Asv.Sdr.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Libs.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Libs.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Libs.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Libs.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
