<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <FileVersion>$(ProductVersion)</FileVersion>
        <Version>$(ProductVersion)</Version>
        <PackageVersion>$(ProductVersion)</PackageVersion>
        <LangVersion>latest</LangVersion>
        <Authors>https://github.com/asv-soft</Authors>
        <Company>https://github.com/asv-soft</Company>
        <Copyright>https://github.com/asv-soft</Copyright>
        <PackageProjectUrl>https://github.com/asv-soft/asv-sdr</PackageProjectUrl>
        <RepositoryUrl>https://github.com/asv-soft/asv-sdr</RepositoryUrl>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Asv.Sdr\Asv.Sdr.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Libs.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Libs.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Libs.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Libs.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
